server:
  port: 5000

attachment:
  aws:
    s3:
      bucket-name: ${ATTACHMENT_AWS_3S_BUCKET_NAME}
      region: ${ATTACHMENT_AWS_3S_REGION}


logging:
  level:
    org:
      hibernate:
        stat: DEBUG
        cache: DEBUG
    com:
      mc:
        hibernate:
          memcached: DEBUG
