server:
  port: 5000

document:
  pdfmake:
    workspace: /var/app/pdfmake-workspace

logging:
  level:
    pico.erp
    shared: DEBUG
    production: DEBUG
    org:
      hibernate:
        stat: DEBUG
        cache: DEBUG
        SQL: DEBUG
        type: TRACE
          BasicTypeRegistry: WARN
